language: node_js
node_js:
- '8'
notifications:
  slack:
    secure: DewI4K4vOFtsiBtL6qGevVu+sticE4eYI9g8k8w+dkrYesLYFhg5Zx2YjBOD3e4YDF+NT3db5ds1Pa6qmJaM2YAV99vZPxfUN2bpnYd4WF1AMGCzXkFFo9inZthn88NLBcb1xd8hkPUnZUZnxbbUqo2Qyzn5nU05LRyeZ6Si+KFJftssDmAnQEILfKn3OmYBRBvKCVYciPTWkUlQdDG3kC3e2sWg4+12xW4E4CMPjbaOJbc/SB5noXZ6VBYozqr5GxRbz3lm7ca3bsR4Ej09yQSIIe2uCUmerVxlMQhrK76wU0zEBhTvCrcB5kekzK5qR+A2elf8vNkS6OgiYgHh/l3uVV6coZ+IVQlnO+aNJ6gaafC5g0zr+DCcfVs6Fxs6Wsz+DB6K8x0128UbGppIQriFP4wjShPJ/iJOsLUCmZipD/qW5FNGXWlXd6ZWo+DSshe8uu/GFW4nqCXFfBBcdNd7z+WzrC983NiObZxHVztTRpqNzJVqXMt01D27G1vaUVCssToQLTi5sZ1hzfduvUTHdBpIQuBrb1vFckUAnYfDC+ynH9Vz+bAfAXOSQ7e47dX9XCwhtkEfOVBcikixilIout2CczhP82LOzMHavEypK608o3LKMcae7BVgj8ezcTx5XrhTeKLagl0+UrwwxVOWeyPPw1Ej5oGsrlUwr/Q=
