version: '3.1'

services:

  devenv:
    image: budak/primo-explore-devenv
    ports:
      - 8003:8003
    volumes:
      - ./test/bootstrap.js:/home/node/primo-explore-devenv/primo-explore/custom/TEST/js/bootstrap.js
      - ./dist/module.js:/home/node/primo-explore-devenv/primo-explore/custom/TEST/js/module.js
